# Generated by Django 4.2.6 on 2023-10-20 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_dentalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
